import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing } from '../constants/theme';

const reasons = ['Higher priority task', 'Blocked', 'Waiting for someone', 'Taking a break', 'Finished for now', 'Other'];
export default function SwitchWork() {
  const { ticketId } = useLocalSearchParams<{ ticketId: string }>(); const router = useRouter(); const db = useSQLiteContext();
  const [summary, setSummary] = useState(''); const [remains, setRemains] = useState(''); const [next, setNext] = useState(''); const [reason, setReason] = useState(reasons[0]); const [saving, setSaving] = useState(false);
  const save = async () => { if (saving) return; setSaving(true); const now = new Date().toISOString(); try { await db.runAsync('INSERT INTO work_sessions (ticket_id, started_at, paused_at, pause_reason, summary, next_action) VALUES (?, ?, ?, ?, ?, ?)', Number(ticketId), now, now, reason, summary.trim(), next.trim()); await db.runAsync('INSERT INTO work_logs (ticket_id, type, description, what_remains, next_action, created_at) VALUES (?, ?, ?, ?, ?, ?)', Number(ticketId), 'other', summary.trim() || 'Paused work session.', remains.trim(), next.trim(), now); await db.runAsync("UPDATE tickets SET status = 'paused', next_action = ?, updated_at = ? WHERE id = ?", next.trim(), now, Number(ticketId)); router.dismissAll(); router.replace('/'); } catch { setSaving(false); } };
  return <SafeAreaView style={s.page} edges={['top', 'bottom']}><KeyboardAvoidingView style={s.keyboard} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><View style={s.nav}><Pressable onPress={() => router.back()}><Text style={s.cancel}>Cancel</Text></Pressable><Text style={s.title}>Switch work</Text><View style={{width: 45}} /></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.heading}>Before you switch...</Text><Text style={s.intro}>Leave a lightweight handoff for your future self.</Text><Label text="What did you accomplish?"/><TextInput value={summary} onChangeText={setSummary} multiline placeholder="A short summary of what changed..." placeholderTextColor={colors.muted} style={[s.input,s.multiline]}/><Label text="What remains?"/><TextInput value={remains} onChangeText={setRemains} multiline placeholder="Anything still open or risky..." placeholderTextColor={colors.muted} style={[s.input,s.multiline]}/><Label text="What should you do next?"/><TextInput value={next} onChangeText={setNext} placeholder="Your first next step" placeholderTextColor={colors.muted} style={s.input}/><Label text="Why are you switching?"/><View style={s.chips}>{reasons.map(x=><Pressable onPress={()=>setReason(x)} key={x} style={[s.chip,reason===x&&s.chipOn]}><Text style={[s.chipText,reason===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</View><Pressable onPress={save} style={s.button}><Text style={s.buttonText}>{saving ? 'Saving...' : 'Save & pause ticket'}</Text></Pressable></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function Label({text}:{text:string}) { return <Text style={s.label}>{text}</Text>; }
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},keyboard:{flex:1},nav:{padding:spacing.lg,flexDirection:'row',justifyContent:'space-between',borderBottomWidth:1,borderColor:colors.line},cancel:{color:colors.muted},title:{color:colors.ink,fontWeight:'800'},content:{padding:spacing.lg,paddingBottom:40},heading:{fontSize:27,fontWeight:'800',color:colors.ink},intro:{color:colors.muted,marginTop:5,lineHeight:20},label:{color:colors.ink,fontWeight:'800',fontSize:13,marginTop:19,marginBottom:8},input:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,padding:13,color:colors.ink,fontSize:15},multiline:{minHeight:78,textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:colors.line,borderRadius:radius.pill,paddingHorizontal:12,paddingVertical:9,backgroundColor:colors.surface},chipOn:{backgroundColor:colors.charcoal,borderColor:colors.charcoal},chipText:{fontSize:12,color:colors.muted,fontWeight:'700'},chipTextOn:{color:'#fff'},button:{backgroundColor:colors.green,borderRadius:radius.md,padding:15,alignItems:'center',marginTop:28},buttonText:{color:'#fff',fontWeight:'800'}});
