import { radius, spacing } from '../constants/theme';
import { useThemedStyles } from './ThemeProvider';

/** Shared layout styles for full-screen modal routes (new ticket, log progress, etc.). */
export function useModalScreenStyles() {
  return useThemedStyles((colors) => ({
    page: { flex: 1, backgroundColor: colors.canvas },
    keyboard: { flex: 1 },
    nav: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: spacing.lg,
      paddingTop: 14,
      paddingBottom: 13,
      borderBottomColor: colors.line,
      borderBottomWidth: 1,
    },
    cancel: { color: colors.muted, fontSize: 14 },
    navTitle: { color: colors.ink, fontWeight: '800', fontSize: 16 },
    navSpacer: { width: 52 },
    loading: {
      flex: 1,
      color: colors.muted,
      textAlign: 'center',
      paddingTop: spacing.lg,
    },
    save: { color: colors.green, fontWeight: '800', fontSize: 14 },
    disabled: { color: colors.muted },
    content: { padding: spacing.lg, paddingBottom: 40 },
    intro: { color: colors.muted, fontSize: 14, lineHeight: 20, marginBottom: 20 },
    label: { color: colors.ink, fontWeight: '800', fontSize: 13, marginTop: 14, marginBottom: 8 },
    optional: { fontSize: 11, color: colors.muted },
    required: { color: colors.green, fontSize: 11 },
    input: {
      backgroundColor: colors.surface,
      borderColor: colors.line,
      borderWidth: 1,
      borderRadius: radius.md,
      color: colors.ink,
      fontSize: 15,
      paddingHorizontal: 13,
      paddingVertical: 12,
    },
    large: { minHeight: 112, textAlignVertical: 'top' },
    medium: { minHeight: 82, textAlignVertical: 'top' },
    multiline: { minHeight: 100, textAlignVertical: 'top' },
    types: { flexGrow: 0 },
    type: {
      backgroundColor: colors.surface,
      borderColor: colors.line,
      borderWidth: 1,
      borderRadius: radius.pill,
      paddingHorizontal: 13,
      paddingVertical: 9,
      marginRight: 7,
    },
    typeSelected: { backgroundColor: colors.charcoal, borderColor: colors.charcoal },
    typeText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
    typeTextSelected: { color: '#fff' },
    button: {
      backgroundColor: colors.green,
      borderRadius: radius.md,
      alignItems: 'center',
      paddingVertical: 15,
      marginTop: 28,
    },
    buttonDisabled: { backgroundColor: colors.line },
    buttonText: { color: '#fff', fontWeight: '800' },
    projects: { flexGrow: 0 },
    project: {
      backgroundColor: colors.surface,
      borderColor: colors.line,
      borderWidth: 1,
      borderRadius: radius.pill,
      paddingHorizontal: 13,
      paddingVertical: 9,
      marginRight: 7,
    },
    projectSelected: { backgroundColor: colors.charcoal, borderColor: colors.charcoal },
    projectText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
    projectTextSelected: { color: '#fff' },
    heading: { fontSize: 27, fontWeight: '800', color: colors.ink },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    chip: {
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: radius.pill,
      paddingHorizontal: 12,
      paddingVertical: 9,
      backgroundColor: colors.surface,
    },
    chipOn: { backgroundColor: colors.charcoal, borderColor: colors.charcoal },
    chipText: { fontSize: 12, color: colors.muted, fontWeight: '700' },
    chipTextOn: { color: '#fff' },
  }));
}
